### PR TITLE
added reveals for algorithm and mixed up code

### PR DESCRIPTION
**Pull request by emkbrown**

### CODE REVIEW

**Comment by bhoffman0** [comment]
It looks like both of you did stringScrambleB. I merged in one, and now there's a conflict with yours. Could you try to resolve the conflicts?  Thanks,
Beryl

**Comment by emkbrown** [comment]
My apologies - there was a miscommunication. I have updated to the other version.

**Comment by bhoffman0** [comment]
Thanks!

**Comment by bhoffman0** [comment]
runestone build gives a lot of errors for stringscrambleb.rst. I think some parts were deleted. Could you take another look at it?

**Pull request merged**
